### PR TITLE
user-list page with status, first name and last name of the users

### PR DESCRIPTION
**Pull request by senolita-git**

### CODE REVIEW

**Review by Laaad — CHANGES_REQUESTED** [review]
Thank you, Sena.

Here's what I tested and what requires change:

- Permissions work properly. I logged in as Admin/User/Sales Rep/Sales Manager and all do see the buttons how they are supposed to see them based on their access rights.
- Clicked on a user name and confirmed that it correctly navigates to the User Details page.
- Opened the Users tab.
- Verified that both First Name and Last Name columns are present.
- Confirmed that the Status column is displayed.
 <hr/>

### Status Label Component:

- Noted that the Status label is not the same `Label` component used on the Deals page.
- Suggested that the Status component should be consistent with the one used on the Deals page.

 <hr/>

**As you mentioned during the stand up:**
### Add Button & Filter Button:

- Noted that the Active / Inactive buttons are still displayed, though they should be changed according to the required design.
- Observed that the Add button is positioned on the right side of the page.
- Noted that the second header must be styled similarly to the Deals page for consistency.
- Observed that the Filter button is missing.

**Review by barissaygili — COMMENTED** [review]
well done Sena

**Comment by senolita-git** [comment]
pushed the fixes. all changes have been made.

**Review by Laaad — APPROVED** [review]
Looks amazing Sena, thank you so much.

**Pull request merged**
